// ============================================================
// Speed Stack: public surface
// ============================================================

export {
  BUDGET_ENFORCE_KILL_SWITCH_ENV,
  BUDGET_WARN_FRACTION,
  buildBudgetEscalationBody,
  buildBudgetExhaustedBody,
  buildBudgetWarnBody,
  evaluateBudgetEnforcement,
  isBudgetEnforcementDisabled,
  type BudgetEnforcementAction,
  type BudgetMessageContext,
  type BudgetStageState,
} from "./budget-enforcement.js";
export {
  DEFAULT_EFFORT_TIER,
  EFFORT_TIERS,
  SUBAGENT_ALLOWANCES,
  THINKING_MODES,
  effortTierToModelOptions,
  findThinkingOffLevel,
  getEffortBehaviorPolicy,
  isPlanThenExecuteEligible,
  isSubagentSpawningAllowed,
  normalizeSpeedStackSessionConfig,
  parseEffortTier,
  parseThinkingMode,
  resolveEffectiveEffortTier,
  resolveEffectiveTurnBudgets,
  resolveThinkingTier,
  type EffortBehaviorPolicy,
  type EffortTier,
  type EffortTierModel,
  type ResolvedThinking,
  type SpeedStackSessionConfig,
  type SubagentAllowance,
  type ThinkingMode,
} from "./effort-tiers.js";
export {
  PLAN_ARTIFACT_FILENAME,
  PLAN_EXECUTE_EXECUTOR_MODEL_ENV,
  PLAN_EXECUTE_EXECUTOR_PREFS_ENV,
  PLAN_EXECUTE_KILL_SWITCH_ENV,
  PLAN_EXECUTE_PLANNER_MAX_STEPS_ENV,
  PLAN_EXECUTE_PLANNER_MAX_TOOL_CALLS_ENV,
  PLAN_EXECUTE_PLANNER_MODEL_ENV,
  DEFAULT_PLANNER_MAX_STEPS,
  DEFAULT_PLANNER_MAX_TOOL_CALLS,
  buildExecutorPrompt,
  buildPlannerPrompt,
  isPlanThenExecuteDisabled,
  parseModelSizeBillions,
  readPlanArtifact,
  readPlanExecuteModelPreferences,
  resolvePlanExecuteModels,
  resolvePlanExecuteSessionDir,
  resolvePlannerBudgets,
  writePlanArtifact,
  type PlanExecuteModelPreferences,
  type PlanExecutePlannerBudgets,
  type PlanExecuteRoleModels,
  type PlanExecuteRouteInput,
} from "./plan-execute.js";
export {
  PLAN_EXECUTE_MULTI_FILE_THRESHOLD,
  PLAN_EXECUTE_SIGNAL_CONFIDENCE_FLOOR,
  decidePlanThenExecute,
  type PlanExecuteGateDecision,
  type PlanExecuteGateInput,
} from "./plan-execute-gate.js";
export {
  SUBAGENT_SPAWN_OVERHEAD_TOKENS,
  buildSubagentPolicyReminderBody,
  isExplicitSubagentRequestInTexts,
  isExplicitSubagentRequestText,
  shouldHideSubagentDispatchTools,
  shouldInjectSubagentGuidanceReminder,
  type SubagentGuidanceInjectionInput,
  type SubagentToolHideInput,
} from "./subagent-guidance.js";
export {
  DEFAULT_RALPH_DONE_MARKER,
  DEFAULT_RALPH_MAX_ITERATIONS,
  appendRalphProgress,
  detectNoProgress,
  normalizeRalphOutput,
  runRalphLoop,
  type RalphLoopConfig,
  type RalphLoopOutcome,
  type RalphStopReason,
} from "./ralph-loop.js";
export {
  normalizeMcpAllowlist,
  pruneMcpServerMap,
  pruneMcpTools,
  type PrunableMcpTool,
} from "./mcp-pruning.js";
export {
  SYSTEMONE_PRUNE_CONFIDENCE_THRESHOLD,
  SYSTEMONE_PRUNE_KILL_SWITCH_ENV,
  SYSTEMONE_KILL_SWITCH_ENV,
  SYSTEMONE_ROUTE_ENDPOINT,
  SYSTEMONE_ROUTE_TIMEOUT_MS,
  applySystemOneEffortOverride,
  fetchSystemOneRouteDecision,
  isSystemOneDisabled,
  resolveEffortTierAndOptions,
  resolveMcpAttachPolicy,
  resolveSystemOneBehaviorPolicy,
  resolveSystemOneModelTarget,
  routeTierMargin,
  type EffortResolution,
  type SystemOneBehaviorPolicyResolution,
  type McpAttachPolicy,
  type McpToolLevelPolicy,
  type ResolveMcpAttachPolicyOptions,
  type SystemOneRouteDecision,
  type SystemOneRouteHolder,
} from "./systemone-route.js";
export {
  TOOL_PACK_CHARS_PER_TOKEN,
  TOOL_PACK_CORE_TOOLS,
  TOOL_PACK_LABEL_TABLE,
  TOOL_PACK_PROTOCOL_TOOLS,
  TOOL_PACK_PRUNE_CONFIDENCE_THRESHOLD,
  buildToolPackRecoveryReminderBody,
  computeServerShortlist,
  computeToolShortlist,
  detectToolPackMissedCalls,
  estimateToolSchemaTokens,
  resolveActiveLabels,
  type CompiledToolPackLabelRule,
  type ComputeServerShortlistInput,
  type ComputeToolShortlistInput,
  type ServerShortlist,
  type ToolPackConfigView,
  type ToolPackLabelRule,
  type ToolPackRouteView,
  type ToolSchemaDescriptor,
  type ToolShortlist,
} from "./tool-packs.js";
export {
  BUDGET_ROUTE_TIERS,
  checkBudgetHit,
  describeTurnBudgets,
  parseBudgetValue,
  resolveTurnBudgets,
  type BudgetHit,
  type BudgetRouteTier,
  type BudgetUsage,
  type TurnBudgets,
} from "./turn-budgets.js";
export {
  ANCHORED_ARCHIVE_KEEP_ENV,
  ANCHORED_COMPACT_KILL_SWITCH_ENV,
  BOUNDARY_COMPACT_WATERMARK_ENV,
  DEFAULT_ANCHORED_ARCHIVE_KEEP,
  DEFAULT_BOUNDARY_COMPACT_WATERMARK,
  EMPTY_ANCHORS,
  archiveSessionTranscript,
  archiveSessionTranscriptWithAnchors,
  buildAnchoredSummaryPrompt,
  combineAnchoredInstructions,
  detectBoundaryEventFromToolCall,
  evaluateBoundaryCompactDecision,
  extractSessionAnchors,
  isAnchoredCompactionEnabled,
  resolveAnchoredArchiveDir,
  resolveArchiveKeepCount,
  resolveBoundaryWatermark,
  rotateSessionArchives,
  type AnchoredArchiveResult,
  type AnchorSourceMessage,
  type BoundaryCompactDecisionInput,
  type BoundaryCompactEventKind,
  type SessionAnchors,
} from "./anchored-compaction.js";
export { buildReviewCommandPrompt, buildVerifyCommandPrompt } from "./verify-review.js";
export {
  DOOM_LOOP_FINAL_STREAK,
  DOOM_LOOP_KILL_SWITCH_ENV,
  DOOM_LOOP_NUDGE_STREAK,
  DOOM_LOOP_STRATEGY_STREAK,
  advanceDoomLoop,
  buildDoomLoopFinalBody,
  buildDoomLoopNudgeBody,
  buildDoomLoopPauseBody,
  buildDoomLoopStrategyBody,
  createDoomLoopTurnState,
  detectDoomLoopTransitions,
  extractDoomLoopTarget,
  fingerprintToolCall,
  isDoomLoopDisabled,
  normalizeDoomLoopValue,
  recordDoomLoopToolUse,
  untriedDoomLoopTools,
  type DoomLoopDetectOptions,
  type DoomLoopObservation,
  type DoomLoopTransition,
  type DoomLoopTurnState,
} from "./doom-loop.js";
